#!/bin/bash
#
# This script copies the contents of the log file
# /var/log/messages to /var/log/messages.old and deletes
# the contents of the /var/log/messages file.
# Usage: ./clearlogs

LOGFILE=/home/dawid/nauka_basha/exercise1/messages

cp $LOGFILE $LOGFILE.old
cat /dev/null > $LOGFILE
echo log file copied and cleaned up

exit 0
