#!/bin/bash

# Usage of here document

wall <<End-of-message
---------------------
This is line 1 of the msg
This is line 2 of the msg
This is last line of the msg
---------------------
End-of-message
