#!/bin/bash

while true; do
	trap "echo NOPE" INT
	pinghost ()
	{
		echo Which host do you want to ping?
		read HOSTNAME
		ping -c 1 $HOSTNAME
	}

	echo 'select option'
	select TASK in 'change password' 'monitor disk space' 'ping a host' 'logout'
	do
		case $REPLY in
			1) TASK=passwd;;
			2) TASK="df -h";;
			3) TASK=pinghost;;
			4) TASK=exit;;
		esac
		if [ -n "$TASK" ]; then
			$TASK
			break
		else
			echo Invalid choice
		fi
	done
done

